### ISSUE TITLE
input question

### ISSUE THREAD

**Issue by HeadReaper-hc** [NicholasMilef/UUO-Mocap#1]
Hi,
   If I only have video input without UUO, can I use this method?

**Comment by NicholasMilef** [comment]
Hi @HeadReaper-hc,

Thanks for your interest in our project! Our method is only designed to work with both video input and UUO markers. There are other works that only use video, so I would encourage you to check these projects out:
* https://github.com/yohanshin/WHAM
* https://github.com/vye16/slahmr

Thanks,
Nick
